export const FETCH_ALL_GISTS = "FETCH_ALL_GISTS";
export const FETCH_ALL_GISTS_ERROR = "FETCH_ALL_GISTS_ERROR";
export const FETCH_SINGLE_GIST_BY_USERNAME = "FETCH_SINGLE_GIST_BY_USERNAME";
export const FETCH_SINGLE_GIST_BY_USERNAME_ERROR =
  "FETCH_SINGLE_GIST_BY_USERNAME_ERROR";
